### PR TITLE
add 404 for several websites

### PR DESCRIPTION
**Pull request by CharaeKeow**

### CODE REVIEW

**Comment by lnfnunes** [comment]
Thank you @CharaeKeow , please solve the conflicts first and we can merge it!

**Comment by CharaeKeow** [comment]
conflicts resolved

**Comment by lnfnunes** [comment]
Sorry @CharaeKeow, I've tried to solve the _new_ conflicts on the Github interface and did something wrong! :/
Could you please fix that and update the PR? Thanks

**Comment by CharaeKeow** [comment]
@Infnunes Sure! ☺️

**Comment by lnfnunes** [comment]
Thanks, @CharaeKeow!
Sorry for the mess I made. Fixed! ;-)

**Pull request merged**
